dist: jammy
language: python

python:
  - "3.11.3"

install:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="ebdjango.settings"

script:
  - python manage.py migrate
  - python manage.py test
